<a href="https://colab.research.google.com/github/vcdemy/20231019/blob/main/20231020%E7%AD%86%E8%A8%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 20231020筆記

## 練習:

用萌典API寫一個中文辭典

API連結: https://www.moedict.tw/uni/

In [ ]:
import requests

In [ ]:
q = "教室"
url = f" https://www.moedict.tw/uni/{q}"

In [ ]:
url

' https://www.moedict.tw/uni/教室'

In [ ]:
data = requests.get(url, verify=False).json()

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.moedict.tw'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(


In [ ]:
data['heteronyms'][0]['definitions'][0]['def']

'學校裡進行教學活動的房間。'

In [ ]:
def lookup(word):
  url = f" https://www.moedict.tw/uni/{word}"
  data = requests.get(url, verify=False).json()
  return data['heteronyms'][0]['definitions'][0]['def']

In [ ]:
lookup('老師')

/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.moedict.tw'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(


'對傳授道業、學問或技藝者的尊稱。'

In [ ]:
# 如果已經有 gradio 就不用再安裝
!pip install gradio

In [ ]:
import gradio as gr

In [ ]:
gr.Interface(lookup, 'text', 'text').launch()

Setting queue=True in a Colab notebook requires sharing enabled. Setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://26f509d4802d9e9bcc.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


## 容器型別複習

* list
* tuple
* dict
* set

In [ ]:
x = list('abcde')

In [ ]:
x

['a', 'b', 'c', 'd', 'e']

In [ ]:
x.append?

In [ ]:
x.append(123)

In [ ]:
x

['a', 'b', 'c', 'd', 'e', 123]

In [ ]:
y = tuple('abcde')

In [ ]:
y

('a', 'b', 'c', 'd', 'e')

In [ ]:
y.count?

In [ ]:
y.count('b')

1

In [ ]:
y.index?

In [ ]:
y.index('d')

3

In [ ]:
z = (1, 2)

In [ ]:
type(z)

tuple

In [ ]:
w = 3, 4

In [ ]:
type(w)

tuple

In [ ]:
w

(3, 4)

In [ ]:
a, b = w

In [ ]:
a

3

In [ ]:
b

4

In [ ]:
u = (1)

In [ ]:
type(u)

int

In [ ]:
v = (1,)

In [ ]:
type(v)

tuple

## 基本語法

* if statements (條件式)
* loops (迴圈)
* functions (函式)
* Exception Handling (例外處理)

### if statements (條件式)

In [ ]:
a = 2
b = 2

In [ ]:
if a > b:
  print('a 大於 b')

a 大於 b


In [ ]:
if a > b:
  print('a 大於 b')
else:
  print('a 沒有大於 b')

a 沒有大於 b


In [ ]:
if a > b:
  print('a 大於 b')
elif a < b:
  print('a 小於 b')
else:
  print('a 等於 b')

a 等於 b


# 練習: (計算BMI)

輸入身高(公尺)、體重(公斤)，計算BMI，然後判斷健康狀況。

$ bmi = \frac{體重(公斤)}{身高(公尺)^2}$

|bmi|健康狀況|
|:-:|:-:|
|bmi<18.5|體重太輕|
|18.5<=bmi<24|健康體重|
|bmi>=24|體重太重|

上面的equation的markdown寫法！
equation的部分可以參考：
https://en.wikibooks.org/wiki/LaTeX/Mathematics

<pre>
$ bmi = \frac{體重(公斤)}{身高(公尺)^2}$

|bmi|健康狀況|
|:-:|:-:|
|bmi<18.5|體重太輕|
|18.5<=bmi<24|健康體重|
|bmi>=24|體重太重|
</pre>

In [ ]:
h = 1.83
w = 80
bmi = 80/(1.83**2)

In [ ]:
bmi

23.888440980620498

In [ ]:
if bmi < 18.5:
  print('體重太輕')
elif bmi >= 24:
  print('體重太重')
else:
  print('健康體重')

健康體重


In [ ]:
def health(h, w):
  bmi = w/(h**2)
  if bmi < 18.5:
    return '體重太輕'
  elif bmi >= 24:
    return '體重太重'
  else:
    return '健康體重'

In [ ]:
# return 跟 print 的差別在有沒有傳東西回 x
x = health(1.83, 80)

In [ ]:
x

'健康體重'

In [ ]:
gr.Interface(health, ["number","number"], "text").launch()

Setting queue=True in a Colab notebook requires sharing enabled. Setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://daa409706ccdad5b6d.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


In [ ]:
def health01(h, w):
  bmi = w/(h**2)
  if bmi < 18.5:
    return bmi, '體重太輕'
  elif bmi >= 24:
    return bmi, '體重太重'
  else:
    return bmi, '健康體重'

In [ ]:
gr.Interface(health01, ["number","number"], ["number","text"]).launch()

Setting queue=True in a Colab notebook requires sharing enabled. Setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://1c11ed8fcf81d1b6a3.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


### 例外處理 (Exception Handling)

In [ ]:
def add(a, b):
  print(f"{a} + {b} = {a+b}")

def sub(a, b):
  print(f"{a} - {b} = {a-b}")

def mul(a, b):
  print(f"{a} * {b} = {a*b}")

def div(a, b):
  print(f"{a} / {b} = {a/b}")

In [ ]:
fns = [add, sub, div, mul]

In [ ]:
for fn in fns:
  fn(1, 2)

1 + 2 = 3
1 - 2 = -1
1 / 2 = 0.5
1 * 2 = 2


In [ ]:
for fn in fns:
  fn(2, 0)

2 + 0 = 2
2 - 0 = 2


ZeroDivisionError: ignored

In [ ]:
for fn in fns:
  try:
    fn(2, 0)
  except Exception as e:
    print(e.args)

2 + 0 = 2
2 - 0 = 2
('division by zero',)
2 * 0 = 0


In [ ]:
f = open('abc.text')
data = f.read()
f.close()

FileNotFoundError: ignored

In [ ]:
try:
  f = open('abc.text')
  data = f.read()
  f.close()
except:
  data = ""

In [ ]:
data

''

In [ ]:
d = {'cat':'貓咪'}
d['dog']

KeyError: ignored

## 資料分析簡介

* numpy: 科學運算基礎套件
* matplotlib: 繪圖基礎套件
* pandas: 資料分析基礎套件

套件載入慣例:

```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```

<pre>
```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```
</pre>

### NumPy (Numerical Python)

* ndarray (N-Dimensional Array)
* ufunc (Universal Functions)

In [1]:
import numpy as np

#### ndarray

In [ ]:
x = [1, 2, 3]
y = [4, 5, 6]

In [ ]:
x + y

[1, 2, 3, 4, 5, 6]

In [ ]:
x*2

[1, 2, 3, 1, 2, 3]

In [ ]:
x1 = np.array(x)
y1 = np.array(y)

In [ ]:
x1

array([1, 2, 3])

In [ ]:
y1

array([4, 5, 6])

In [ ]:
x1 + y1

array([5, 7, 9])

In [ ]:
x1 * 2

array([2, 4, 6])

#### 顯示ndarray的屬性

In [ ]:
x1

array([1, 2, 3])

In [ ]:
x1.dtype

dtype('int64')

In [ ]:
x1.shape

(3,)

#### ndarray的操作

In [ ]:
# np.arange()類似range()的ndarray版
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [2]:
G = np.arange(25)

In [3]:
G

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
G.shape

(25,)

In [5]:
G.shape = 5, 5

In [6]:
G

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
L = [[ 0,  1,  2,  3,  4],
     [ 5,  6,  7,  8,  9],
     [10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19],
     [20, 21, 22, 23, 24]]

##### indexing & slicing

In [ ]:
len?

In [8]:
# len會回傳L裡面的element的個數
len(L)

5

In [10]:
L[2]

[10, 11, 12, 13, 14]

In [11]:
L[2][2]

12

In [12]:
G[2][2]

12

In [13]:
L

[[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24]]

In [14]:
L[1:3][1:3]

[[10, 11, 12, 13, 14]]

In [15]:
L[1:3]

[[5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [16]:
G[1:3][1:3]

array([[10, 11, 12, 13, 14]])

In [17]:
G[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [18]:
G[2, 2]

12

In [19]:
G

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
import plotly.express as px

In [25]:
px.imshow(G, color_continuous_scale='gray')

In [26]:
G

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
G[0] = 0
G[:, 0] = 0
G[-1] = 0
G[:, -1] = 0

In [32]:
G

array([[ 0,  0,  0,  0,  0],
       [ 0,  6,  7,  8,  0],
       [ 0, 11, 12, 13,  0],
       [ 0, 16, 17, 18,  0],
       [ 0,  0,  0,  0,  0]])

In [33]:
px.imshow(G, color_continuous_scale='gray')

In [37]:
import gradio as gr

In [35]:
def process(image):
  image[:,:,1:] = 0
  return image

In [38]:
gr.Interface(process, "image", "image").launch()

Setting queue=True in a Colab notebook requires sharing enabled. Setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://3e9003c6af9346447c.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


In [88]:
np.arange(25).dtype

dtype('int64')

In [89]:
R = np.arange(25).reshape(5, 5)*10

In [90]:
R

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240]])

In [91]:
R.dtype

dtype('int64')

In [92]:
R = R.astype("uint8")

In [61]:
G = np.arange(25)[::-1].reshape(5, 5)*10

In [80]:
G = R.astype("uint8")

In [97]:
B = np.zeros_like(G)

In [98]:
B = B + 255

In [99]:
B = B.astype('uint8')

In [101]:
RGB = np.dstack((R, G, B))

In [102]:
RGB[0, 0]

array([  0,   0, 255], dtype=uint8)

In [103]:
px.imshow(RGB)

In [85]:
def process(image):
  m, n = image.shape[:2]
  return image[m//3:m*2//3, n//3:n*2//3]

In [86]:
gr.Interface(process, "image", "image").launch()

Setting queue=True in a Colab notebook requires sharing enabled. Setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://e478f0b022e03527ba.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


In [115]:
gr.Interface(process, "webcam", "image").launch()

Setting queue=True in a Colab notebook requires sharing enabled. Setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://385c39a3e179e69784.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


#### ndarray的加法及乘法

In [104]:
x = [1, 2, 3]

In [105]:
y = [4, 5, 6]

In [106]:
x1 = np.array(x)
y1 = np.array(y)

In [108]:
x1 + y1

array([5, 7, 9])

In [109]:
x1 * 2

array([2, 4, 6])

In [110]:
x1 + 10

array([11, 12, 13])

In [111]:
x1 = x1 + 10

In [112]:
x1

array([11, 12, 13])

In [113]:
x1 = 10

In [114]:
x1

10

### ufunc

In [117]:
import math

In [118]:
math.sin(math.pi/2)

1.0

In [116]:
x

[1, 2, 3]

In [119]:
math.sin(x)

TypeError: ignored

In [120]:
np.sin(np.pi/2)

1.0

In [121]:
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])

### pandas

* Series
* DataFrame

In [123]:
!pip install yfinance

In [124]:
import yfinance as yf

In [131]:
df = yf.download('TSLA')

[*********************100%%**********************]  1 of 1 completed


In [132]:
type(df)

pandas.core.frame.DataFrame

#### 檢視資料

In [138]:
df.head?

In [135]:
df.head()

Open      High       Low     Close  Adj Close     Volume
Date                                                                    
2010-06-29  1.266667  1.666667  1.169333  1.592667   1.592667  281494500
2010-06-30  1.719333  2.028000  1.553333  1.588667   1.588667  257806500
2010-07-01  1.666667  1.728000  1.351333  1.464000   1.464000  123282000
2010-07-02  1.533333  1.540000  1.247333  1.280000   1.280000   77097000
2010-07-06  1.333333  1.333333  1.055333  1.074000   1.074000  103003500

In [136]:
df.tail()

Open        High         Low       Close   Adj Close  \
Date                                                                     
2023-10-13  258.899994  259.600006  250.220001  251.119995  251.119995   
2023-10-16  250.050003  255.399994  248.479996  253.919998  253.919998   
2023-10-17  250.100006  257.179993  247.080002  254.850006  254.850006   
2023-10-18  252.699997  254.630005  242.080002  242.679993  242.679993   
2023-10-19  225.949997  230.610001  216.779999  220.110001  220.110001   

               Volume  
Date                   
2023-10-13  102073800  
2023-10-16   88917200  
2023-10-17   93562900  
2023-10-18  125147800  
2023-10-19  170110800

In [137]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 3351 entries, 2010-06-29 to 2023-10-19
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Open       3351 non-null   float64
 1   High       3351 non-null   float64
 2   Low        3351 non-null   float64
 3   Close      3351 non-null   float64
 4   Adj Close  3351 non-null   float64
 5   Volume     3351 non-null   int64  
dtypes: float64(5), int64(1)
memory usage: 183.3 KB


In [139]:
df[:5]

Open      High       Low     Close  Adj Close     Volume
Date                                                                    
2010-06-29  1.266667  1.666667  1.169333  1.592667   1.592667  281494500
2010-06-30  1.719333  2.028000  1.553333  1.588667   1.588667  257806500
2010-07-01  1.666667  1.728000  1.351333  1.464000   1.464000  123282000
2010-07-02  1.533333  1.540000  1.247333  1.280000   1.280000   77097000
2010-07-06  1.333333  1.333333  1.055333  1.074000   1.074000  103003500

#### 讀取單一個欄位

In [140]:
df['Close']

Date
2010-06-29      1.592667
2010-06-30      1.588667
2010-07-01      1.464000
2010-07-02      1.280000
2010-07-06      1.074000
                 ...    
2023-10-13    251.119995
2023-10-16    253.919998
2023-10-17    254.850006
2023-10-18    242.679993
2023-10-19    220.110001
Name: Close, Length: 3351, dtype: float64

In [141]:
type(df['Close'])

pandas.core.series.Series